import {
  OLD_TULIP_ADDRESS,
  OLD_BUD_ADDRESS,
  OLD_PETAL_ADDRESS,
  GENESIS_POOLS_ADDRESS,
  USDT_ADDRESS,
  WROSE_ADDRESS,
  TSWAP_ADDRESS,
} from "config/constants";
import TulipGenesisRewardPool from "abis/TulipGenesisRewardPool.json";
import TULIP_LOGO from "assets/img/twotulip.png";
import BUD_LOGO from "assets/img/onetulip.png";
import PETAL_LOGO from "assets/img/threetulip.png";
import WROSE_LOGO from "assets/img/fourtulip.png";
import USDT_LOGO from "assets/img/fivetulip.png";
import TSWAP_LOGO from "assets/img/sixtulip.png";
import PetalGenesisRewardPool from "abis/PetalGenesisRewardPool.json";

const PETAL_CHEF_ADDRESS = "0x096132Bd5645E8C88dDBa70E29408e71abf2C909";
const PETAL_REWARD_POOL_ADDRESS = "0x16Fbb2aE6519a27809fef8e9E1290D27bA143Dfe";

export const LiquidationPools = {
  OldBudGenesisPool: {
    abi: TulipGenesisRewardPool.abi,
    address: GENESIS_POOLS_ADDRESS,
    logo: BUD_LOGO,
    pool: "OldBudGenesisPool",
    icon: "",
    defaultTokenPrice: "0.06",
    name: "$TOKEN - $TOKEN LP",
    depositToken: "OLD-BUD",
    earnToken: "TLP",
    _pid: 0,
    tokenName: "OLD BUD",
    depositTokenAddress: OLD_BUD_ADDRESS,
    finished: false,
    closedForStaking: false,
    RATIO: 220 / 800,
    decimals: 18,
  },
  OldTulipGenesisPool: {
    abi: TulipGenesisRewardPool.abi,
    address: GENESIS_POOLS_ADDRESS,
    logo: TULIP_LOGO,
    pool: "OldTulipGenesisPool",
    icon: "",
    defaultTokenPrice: "0.05",
    name: "$TOKEN - $TOKEN LP",
    depositToken: "OLD-TULIP",
    earnToken: "TLP",
    _pid: 1,
    tokenName: "OLD TULIP",
    depositTokenAddress: OLD_TULIP_ADDRESS,
    finished: false,
    closedForStaking: false,
    RATIO: 175 / 800,
    decimals: 18,
  },
  OldPetalGenesisPool: {
    abi: TulipGenesisRewardPool.abi,
    address: GENESIS_POOLS_ADDRESS,
    logo: PETAL_LOGO,
    pool: "OldPetalGenesisPool",
    icon: "",
    defaultTokenPrice: "3.34",
    name: "$TOKEN - $TOKEN LP",
    depositToken: "OLD-PETAL",
    earnToken: "TLP",
    _pid: 2,
    tokenName: "OLD PETAL",
    depositTokenAddress: OLD_PETAL_ADDRESS,
    finished: false,
    closedForStaking: false,
    RATIO: 175 / 800,
    decimals: 18,
  },
  WroseGenesisPool: {
    abi: TulipGenesisRewardPool.abi,
    address: GENESIS_POOLS_ADDRESS,
    logo: WROSE_LOGO,
    pool: "WroseGenesisPool",
    icon: "",
    defaultTokenPrice: "0.23",
    name: "$TOKEN - $TOKEN LP",
    depositToken: "wROSE",
    earnToken: "TLP",
    _pid: 3,
    tokenName: "wROSE",
    depositTokenAddress: WROSE_ADDRESS,
    finished: false,
    closedForStaking: false,
    RATIO: 100 / 800,
    decimals: 18,
  },
  UsdtGenesisPool: {
    abi: TulipGenesisRewardPool.abi,
    address: GENESIS_POOLS_ADDRESS,
    logo: USDT_LOGO,
    pool: "UsdtGenesisPool",
    icon: "",
    defaultTokenPrice: "1.00",
    name: "$TOKEN - $TOKEN LP",
    depositToken: "USDT",
    earnToken: "TLP",
    _pid: 4,
    tokenName: "USDT",
    depositTokenAddress: USDT_ADDRESS,
    finished: false,
    closedForStaking: false,
    RATIO: 50 / 800,
    decimals: 6,
  },
  TswapGenesisPool: {
    abi: TulipGenesisRewardPool.abi,
    address: GENESIS_POOLS_ADDRESS,
    logo: TSWAP_LOGO,
    pool: "TswapGenesisPool",
    icon: "",
    defaultTokenPrice: "0.015",
    name: "$TOKEN - $TOKEN LP",
    depositToken: "TSWAP",
    earnToken: "TLP",
    _pid: 6,
    tokenName: "TSWAP",
    depositTokenAddress: TSWAP_ADDRESS,
    finished: false,
    closedForStaking: false,
    RATIO: 100 / 800,
    decimals: 18,
  },
  OldPetalToPetalGenesisPool: {
    abi: PetalGenesisRewardPool.abi,
    address: PETAL_CHEF_ADDRESS,
    logo: PETAL_LOGO,
    pool: "OldPetalToPetalGenesisPool",
    icon: "",
    defaultTokenPrice: "3.34",
    name: "$TOKEN - $TOKEN LP",
    depositToken: "OLD-PETAL",
    earnToken: "PTL",
    _pid: 0,
    tokenName: "OLD-PETAL",
    depositTokenAddress: OLD_PETAL_ADDRESS,
    finished: false,
    closedForStaking: false,
    RATIO: 100 / 100,
    decimals: 18,
  },

  TlpWrosePool: {
    abi: PetalGenesisRewardPool.abi,
    address: PETAL_REWARD_POOL_ADDRESS,
    logo: TULIP_LOGO,
    pool: "TlpWrosePool",
    icon: "",
    defaultTokenPrice: "100",
    name: "$TOKEN - $TOKEN LP",
    depositToken: "TLP-WROSE",
    earnToken: "PTL",
    _pid: 0,
    tokenName: "TLP-WROSE",
    depositTokenAddress: "0x4a924044481ba5aa70e833e39ffc186c4698388d",
    finished: false,
    closedForStaking: false,
    RATIO: 200 / 280,
    decimals: 18,
  },
  PtlWrosePool: {
    abi: PetalGenesisRewardPool.abi,
    address: PETAL_REWARD_POOL_ADDRESS,
    logo: PETAL_LOGO,
    pool: "PtlWrosePool",
    icon: "",
    defaultTokenPrice: "100",
    name: "$TOKEN - $TOKEN LP",
    depositToken: "PTL-WROSE",
    earnToken: "PTL",
    _pid: 1,
    tokenName: "PTL-WROSE",
    depositTokenAddress: "0x8584444c6DfBEFbA94dCF2F2Aa7CbC66d456609A",
    finished: false,
    closedForStaking: false,
    RATIO: 80 / 280,
    decimals: 18,
  },
};

export default LiquidationPools;
