import ChefRewardPool from 'abis/TulipSwapChef.json'

import TulipPetalLogo from 'assets/img/tulip-petal-lp.png'
import TSwapLogo from 'assets/img/currency_logos/tswap-transparent.png'
import OapeLogo from 'assets/img/currency_logos/oape.png'

import USDCLogo from 'assets/img/currency_logos/USDC.png'
import USDTLogo from 'assets/img/currency_logos/usdt_new.png'
import EthLogo from 'assets/img/currency_logos/eth.png'
import FtmLogo from 'assets/img/currency_logos/FTM.png'

const CHEF_ADDRESS = '0x624FDD79e30cb04924c68dcC7fc4EC4e85FbDe70'

const farmConfig = {
  TswapWroseTswapPool: {
    abi: ChefRewardPool.abi,
    address: CHEF_ADDRESS,
    logo: TSwapLogo,
    pool: 'TswapWroseTswapPool',
    poolId: 0,
    icon: '',
    token0: 'TSWAP',
    token1: 'wROSE',
    name: 'Deposit $TSWAP-wROSE LP IN FAMILY POOL & Earn TSWAP',
    depositToken: 'TSWAP',
    earnToken: 'TSWAP',
    _pid: 0,
    tokenName: 'TSWAP/wROSE LP',
    tokenAddress: '0x3fc7f82D82E27cA3d24CF9A09559Cb28B4d47E91',
    usesBoth: false,
    usesPetal: false,
    finished: false,
    closedForStaking: false,
    usesRose: true,
    RATIO: 3500 / 6650,
    exchange: 'TSWAP',
  },
  USDTWroseTswapPool: {
    abi: ChefRewardPool.abi,
    usesRose: true,
    address: CHEF_ADDRESS,
    logo: USDTLogo,
    pool: 'USDTWroseTswapPool',
    poolId: 1,
    icon: '',
    token0: 'USDT',
    token1: 'wROSE',
    name: 'Deposit $USDT-wROSE LP IN FAMILY POOL & Earn TSWAP',
    depositToken: 'TSWAP',
    earnToken: 'TSWAP',
    _pid: 1,
    tokenName: 'USDT/wROSE LP',
    tokenAddress: '0xc0a73bA79CD7d62CCbEA48499FdcCF2f915e3f75',
    usesBoth: false,
    usesPetal: false,
    finished: false,
    closedForStaking: false,
    RATIO: 1100 / 6650,
    exchange: 'TSWAP',
  },
  USDCWroseTswapPool: {
    usesRose: true,
    abi: ChefRewardPool.abi,
    address: CHEF_ADDRESS,
    logo: USDCLogo,
    usesUSDC: true,
    pool: 'USDCWroseTswapPool',
    poolId: 2,
    icon: '',
    token0: 'USDC',
    token1: 'wROSE',
    name: 'Deposit $USDC-wROSE LP IN FAMILY POOL & Earn TSWAP',
    depositToken: 'TSWAP',
    earnToken: 'TSWAP',
    _pid: 2,
    tokenName: 'USDC/wROSE LP',
    tokenAddress: '0x267Dac31680d790ED19b558b804dfd2F3E6C5987',
    usesBoth: false,
    usesPetal: false,
    finished: false,
    closedForStaking: false,
    RATIO: 600 / 6650,
    exchange: 'TSWAP',
  },
  TulipPetalTswapPool: {
    abi: ChefRewardPool.abi,
    address: CHEF_ADDRESS,
    logo: TulipPetalLogo,
    pool: 'TulipPetalTswapPool',
    poolId: 3,
    icon: '',
    token0: 'TULIP',
    token1: 'PETAL',
    name: 'Deposit $TULIP-PETAL LP IN FAMILY POOL & Earn TSWAP',
    depositToken: 'TSWAP',
    earnToken: 'TSWAP',
    _pid: 3,
    tokenName: 'TULIP/PETAL LP',
    tokenAddress: '0x1786a82aB9927004134C76AE37eeEc9C7B0a90CB',
    usesBoth: true,
    usesPetal: false,
    finished: false,
    closedForStaking: false,
    RATIO: 1100 / 6650,
    exchange: 'TSWAP',
  },
  WETHWroseTswapPool: {
    usesRose: true,
    abi: ChefRewardPool.abi,
    address: CHEF_ADDRESS,
    logo: EthLogo,
    pool: 'WETHWroseTswapPool',
    poolId: 4,
    icon: '',
    token0: 'WETH',
    token1: 'wROSE',
    name: 'Deposit $WETH-wROSE LP IN FAMILY POOL & Earn TSWAP',
    depositToken: 'TSWAP',
    earnToken: 'TSWAP',
    _pid: 4,
    tokenName: 'WETH/wROSE LP',
    tokenAddress: '0x340DeCca6608d58D086d58CbE943419aE8371F92',
    usesBoth: false,
    usesPetal: false,
    finished: false,
    closedForStaking: false,
    RATIO: 250 / 6650,
    exchange: 'TSWAP',
  },
  UsdcUsdtTswapPool: {
    usesUSDC: true,
    abi: ChefRewardPool.abi,
    address: CHEF_ADDRESS,
    logo: USDCLogo,
    pool: 'UsdcUsdtTswapPool',
    poolId: 5,
    icon: '',
    token0: 'USDC',
    token1: 'USDT',
    name: 'Deposit $USDC-USDT LP IN FAMILY POOL & Earn TSWAP',
    depositToken: 'TSWAP',
    earnToken: 'TSWAP',
    _pid: 5,
    tokenName: 'USDC/USDT LP',
    tokenAddress: '0x54FfC08F5E75bbE16945b71db122CB398298eBBF',
    usesBoth: false,
    usesPetal: false,
    finished: false,
    closedForStaking: false,
    RATIO: 250 / 6650,
    exchange: 'TSWAP',
  },
  WftmWroseTswapPool: {
    abi: ChefRewardPool.abi,
    address: CHEF_ADDRESS,
    logo: FtmLogo,
    pool: 'WftmWroseTswapPool',
    poolId: 6,
    icon: '',
    token0: 'WFTM',
    token1: 'WROSE',
    name: 'Deposit $WFTM-WROSE LP IN FAMILY POOL & Earn TSWAP',
    depositToken: 'TSWAP',
    earnToken: 'TSWAP',
    _pid: 6,
    tokenName: 'WFTM/WROSE LP',
    tokenAddress: '0x0bB9A5327Be932aA9DE8aE72079BD9D9347e854A',
    usesBoth: false,
    usesPetal: false,
    finished: false,
    usesRose: true,
    closedForStaking: false,
    RATIO: 250 / 6650,
    exchange: 'TSWAP',
  },
  OapeTulipTswapPool: {
    abi: ChefRewardPool.abi,
    address: CHEF_ADDRESS,
    logo: OapeLogo,
    pool: 'OapeTulipTswapPool',
    poolId: 7,
    icon: '',
    token0: 'OAPE',
    token1: 'TULIP',
    name: 'Deposit $OAPE-TULIP LP IN FAMILY POOL & Earn TSWAP',
    depositToken: 'TSWAP',
    earnToken: 'TSWAP',
    _pid: 7,
    tokenName: 'OAPE/TULIP LP',
    tokenAddress: '0x6D34f2388ec0427A0dE3814921F613CA7e4C5342',
    usesBoth: false,
    usesTulip: true,
    usesPetal: false,
    finished: false,
    closedForStaking: false,
    RATIO: 100 / 6650,
    exchange: 'TSWAP',
  },
  TswapSingleTswapPool: {
    abi: ChefRewardPool.abi,
    address: CHEF_ADDRESS,
    logo: TSwapLogo,
    pool: 'TswapSingleTswapPool',
    poolId: 8,
    icon: '',
    token0: 'TSWAP',
    token1: 'TSWAP',
    name: 'Deposit $TSWAP LP IN FAMILY POOL & Earn TSWAP',
    depositToken: 'TSWAP',
    earnToken: 'TSWAP',
    _pid: 8,
    tokenName: 'SINGLE STAKE TSWAP',
    tokenAddress: '0x41856cC5aB63Ab79142462BC667fdfaE0Fb80775',
    usesBoth: false,
    usesTulip: false,
    usesPetal: false,
    usesTswap: true,
    finished: false,
    closedForStaking: false,
    RATIO: 300 / 6650,
    exchange: 'TSWAP',
    singleStaked: true,
  },
}

export default farmConfig
